# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rspec'
gem 'test-unit', '~> 3.3', '>= 3.3.4'
gem 'byebug'
